version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
               - cd deployment
               - sed -i -e 's/\r$//' deploy.sh
               -  /bin/bash deploy.sh reuse1-dev dev