AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  SiteName:
    Description: The name of the site for which the stack is created.
    Type: String
    MinLength: '3'
    MaxLength: '24'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9_.-]*'

Resources:
  #SSM Parameters
  MyTestParam:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Sub '/${SiteName}/ReuseServer/MyTestParam'
      Description: 'Test Param'
      Type: 'String'
      Value: '2'
